In [61]:
# Upload converted csv from
# https://travel.state.gov/content/travel/en/legal/visa-law0/visa-statistics/annual-reports.html

from google.colab import files

print("Please upload your CSV file.")
uploaded = files.upload()

file_path_1 = next(iter(uploaded))

Please upload your CSV file.

Saving visa issuance.csv to visa issuance.csv

In [62]:
import pandas as pd

df = pd.read_csv("visa issuance.csv")

df = df.set_index('Issuing Office')

print(df.head())

                            2015  2016  2017  2018  2019  2020  2021  2022  \
Issuing Office
Angola, Luanda             11330  6859  7670  7538  4904  1866  1394  3873
Benin, Cotonou              1822  1793  1540  1488  1426   767   205  1206
Botswana, Gaborone          1982  2103  1847  1719  1862   816   222  2698
Burkina Faso, Ouagadougou   5450  5926  2609  1979  2260   900   381  2799
Burundi, Bujumbura          1102  1113  1451   890   759   226   284   884

                           2023  2024
Issuing Office
Angola, Luanda             5446  5812
Benin, Cotonou             1884  2550
Botswana, Gaborone         2696  2383
Burkina Faso, Ouagadougou  2235  2624
Burundi, Bujumbura         1369  1228

In [63]:
df.dropna()

,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Issuing Office,,,,,,,,,,
"Angola, Luanda",11330,6859,7670,7538,4904,1866,1394,3873,5446,5812
"Benin, Cotonou",1822,1793,1540,1488,1426,767,205,1206,1884,2550
"Botswana, Gaborone",1982,2103,1847,1719,1862,816,222,2698,2696,2383
"Burkina Faso, Ouagadougou",5450,5926,2609,1979,2260,900,381,2799,2235,2624
"Burundi, Bujumbura",1102,1113,1451,890,759,226,284,884,1369,1228
...,...,...,...,...,...,...,...,...,...,...
"Peru, Lima",109330,93352,96267,92633,107847,56296,53133,69721,106554,149671
"Suriname, Paramaribo",6567,4971,5441,5801,6912,2654,1480,6012,7403,6743
"Trinidad and Tobago, Port of Spain",27662,32302,28126,26953,39026,18322,8517,25418,49796,55991
"Uruguay, Montevideo",28916,29857,26750,25263,22733,9081,10325,23351,30063,33066
"Venezuela, Caracas",239772,151014,47942,21290,4614,0,0,0,0,0

In [67]:
# There's so many issuing offices, let's merge them and sort them by country!
df_country = df.copy()
df_country['Country'] = df_country.index.str.split(',').str[0]
df_aggregated = df_country.groupby('Country').sum()
df_clean = df_aggregated.loc[~(df_aggregated == 0).all(axis=1)]
df_clean.shape

(168, 10)

In [68]:
df_clean

,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Country,,,,,,,,,,
Afghanistan,3063,2723,1902,1552,1554,856,535,0,0,0
Albania,6600,8524,10001,12153,11489,6982,5524,14423,25483,25731
Algeria,11855,13704,11353,12888,12272,5137,691,11613,19240,19142
Angola,11330,6859,7670,7538,4904,1866,1394,3873,5446,5812
Argentina,249293,303897,360891,334430,222043,90187,39256,219375,288110,289971
...,...,...,...,...,...,...,...,...,...,...
Venezuela,239772,151014,47942,21290,4614,0,0,0,0,0
Vietnam,101221,104830,121118,123416,131093,64050,35212,92912,127380,144974
Yemen,656,0,0,0,0,0,0,0,0,0
Zambia,3752,4021,4365,4747,3736,1350,1049,6111,8081,3978
Zimbabwe,5288,5842,5955,5852,6079,2378,2817,6038,8118,10698

In [69]:
# Export Dataframe into CSV
df_clean.to_csv('visa_issuance.csv')